data:
  - monitoring:
      directory: 'D:\logs\jeju_ontune\pgsql_log'
      pattern: 'yyyy-MM-DD_HHmmss'
      file: postgresql-
      extension: log
    interval: 1
    name: jeju_pg
    type: normal
    words:
    - 'does not exist'
    - 'fatal'
    - 'error'
    - 'closed'
    initial-training: false
    snapshot-file: jeju_postgresql.bin
    mode: training
    report: false
    similarity-threshold: 1

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTune_log'
      pattern: day
      file: ontunelog
      extension: txt
      date-time-format: 'yyyy MM-dd HH-mm-ss'
    interval: 1
    name: jeju_onTune
    type: normal
    words:
    - 'error'
    - 'fail'
    - 'terminated'
    initial-training: false
    snapshot-file: ontunemanager_log.bin
    mode: training
    report: false
    similarity-threshold: 1

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: day
      file: ontuneeventlog
      extension: txt
    interval: 10
    name: jeju_onTuneEvent
    type: normal
    words:
    - 'error'
    - 'nok'    
    initial-training: false
    snapshot-file: ontuneevent_log.bin
    mode: training
    report: false
    similarity-threshold: 1

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: day
      file: ontuneeventstatuslog
      extension: txt
    interval: 10
    name: jeju_onTuneEventStatus
    type: normal
    initial-training: true
    snapshot-file: ontuneevent_status_log.bin
    mode: training
    report: true
    similarity-threshold: 1

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: none
      file: notification_sms_log_0
      extension: txt
      date-time-format: 'yyyy MM-dd HH:mm:ss.fff'
    interval: 10
    name: jeju_onTuneEventNoti
    type: normal
    words:
    - 'does not exist'
    - 'error'
    - 'nok'
    - 'timeout'
    initial-training: true
    snapshot-file: ontuneevent_noti_log.bin
    mode: training
    report: true
    similarity-threshold: 0.9

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: none
      file: onTuneEventViewerLog
      extension: txt
    interval: 10
    name: jeju_onTuneEventViewer
    type: normal
    words:
    - 'error'
    - 'fail'
    - 'does not exist'
    initial-training: false
    snapshot-file: ontuneevent_viewer_log.bin
    mode: training
    report: false
    similarity-threshold: 1

  - monitoring:
      directory: 'windows_event_log'
      pattern: none
      file: eventlog
      extension: txt
    interval: 1
    name: windows-event
    type: windows-event
    initial-training: true
    snapshot-file: windows-event.bin
    mode: training
    report: true
    similarity-threshold: 1