data:
  - monitoring:
      directory: 'D:\logs\jeju_ontune\pgsql_log'
      pattern: '(\d{4})\-(\d{2})-(\d{2})_(\d{6})'
      file: postgresql-
      extension: log
    interval: 1
    name: jeju_pg
    type: normal
    initial-training: true
    snapshot-file: jeju_postgresql.bin
    mode: training
    report: true
    similarity-threshold: 0.1

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTune_log'
      pattern: day
      file: ontunelog
      extension: txt
    interval: 1
    name: jeju_onTune
    type: normal
    initial-training: true
    snapshot-file: jeju_ontunemanager_log.bin
    mode: training
    report: true
    similarity-threshold: 0.05

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: day
      file: ontuneeventlog
      extension: txt
    interval: 10
    name: jeju_onTuneEvent
    type: normal
    initial-training: true
    snapshot-file: jeju_ontuneevent_log.bin
    mode: training
    report: true
    similarity-threshold: 0.3

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: day
      file: ontuneeventstatuslog
      extension: txt
    interval: 10
    name: jeju_onTuneEventStatus
    type: normal
    initial-training: true
    snapshot-file: jeju_ontuneevent_status_log.bin
    mode: training
    report: true
    similarity-threshold: 0.6

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: none
      file: notification_sms_log_0
      extension: txt
    interval: 10
    name: jeju_onTuneEventNoti
    type: normal
    initial-training: true
    snapshot-file: jeju_ontuneevent_noti_log.bin
    mode: training
    report: true
    similarity-threshold: 0.7

  - monitoring:
      directory: 'D:\logs\jeju_ontune\onTuneEvent_log'
      pattern: none
      file: onTuneEventViewerLog
      extension: txt
    interval: 10
    name: jeju_onTuneEventViewer
    type: normal
    initial-training: true
    snapshot-file: jeju_ontuneevent_viewer_log.bin
    mode: training
    report: true
    similarity-threshold: 0.6

  - monitoring:
      directory: 'windows_event_log'
      pattern: none
      file: eventlog
      extension: txt
      exception-words:
    interval: 1
    name: windows-event
    type: windows-event
    initial-training: true
    snapshot-file: windows-event.bin
    mode: training