data:
  - monitoring:
      directory: 'C:\sksktest'
      pattern: none
      file: ontunelog_230329
      extension: txt
    interval: 1
    name: sksk
    type: normal
    initial-training: true
    snapshot-file: sksktest.bin
    mode: training

  - monitoring:
      directory: 'D:\ontunemanager\log2'
      pattern: day
      file: ontunelog
      extension: txt
    interval: 1
    name: onTune
    type: normal
    initial-training: true
    snapshot-file: ontunemanager_log.bin
    mode: training

  - monitoring:
      directory: 'windows_event_log'
      pattern: none
      file: eventlog
      extension: txt
    interval: 1
    name: windows-event
    type: windows-event
    initial-training: false
    snapshot-file: windows-event.bin
    mode: training