data:
  - monitoring:
      directory: 'C:\sksktest'
      pattern: none
      file: ontunelog_230330
      extension: txt
      date-time-format: 'yyyy MM-dd HH-mm-ss %MSG'
      exception-words:
        - 'is started'
        - 'connected database'
        - 'select *'
    interval: 1
    name: sksk
    type: normal
    initial-training: false
    snapshot-file: sksktest.bin
    mode: training
    

  - monitoring:
      directory: 'windows_event_log'
      pattern: none
      file: eventlog
      extension: txt
      exception-words:
    interval: 1
    name: windows-event
    type: windows-event
    initial-training: false
    snapshot-file: windows-event.bin
    mode: training